spring:
  application:
    name: feign
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    web: debug
    org.springframework.cloud.openfeign: debug
